### ISSUE TITLE
What is the name for this plugin at the NPM website ?

### ISSUE THREAD

**Issue by BobbyBabes** [4lejandrito/rollup-plugin-browsersync#2]
Or is it deliberate that this plugin can not be found by the search function at the NPM website ? :
[https://www.npmjs.com/search?q=rollup-plugin-browsersync](https://www.npmjs.com/search?q=rollup-plugin-browsersync)

**Comment by 4lejandrito** [comment]
Hi!

I think NPM search has been malfunctioning lately. That same URL you pasted works for me today. That is the right name.

Closing for now.

**Comment by BobbyBabes** [comment]
Hi,
Must have been. I'll check it out later today. :)
